### ISSUE TITLE
OPGG error

### ISSUE THREAD

**Issue by ketiasd** [VOTRON157/lobby-reveal#1]
Hi! 

Can you help me? im getting a HTTP 442 error in the opgg page.

**Comment by VOTRON157** [comment]
This error never happened to me during development, but if you have some programming knowledge, you can modify the code to display the summoners' names directly on the console, allowing you to manually search on opgg. It's worth noting that this code was only tested on the BR server, and I don't know if it works on other servers.

**Comment by VOTRON157** [comment]
> This error never happened to me during development, but if you have some programming knowledge, you can modify the code to display the summoners' names directly on the console, allowing you to manually search on opgg. It's worth noting that this code was only tested on the BR server, and I don't know if it works on other servers.

I just found out the reason for this error - it occurs because the region is invalid (https://www.op.gg/multisearch/invalid?summoners=test3,test2,test1 is an example of an invalid region). Your client probably isn't providing your region. I made a modification to the code to display the summoners' names in the terminal, so you can manually access op.gg and search according to your region. Additionally, I added a feature so that if the client cannot find your region, the default region used will be EUW.

**Comment by ketiasd** [comment]
Thanks! im from LAS now it's working :D
